### PR TITLE
update china ip and support external china ip list

### PR DESCRIPTION
**Pull request by skiyer**
“china_ip_list.txt” under the same directory will be used

### CODE REVIEW

**Comment by netheril96** [comment]
What is the difference between the new link and old for China IP?

**Comment by skiyer** [comment]
Generally, china ip list from ipip.net are more accurate.
https://github.com/17mon/china_ip_list
http://www.infoq.com/cn/articles/ip-gch-interview

**Comment by netheril96** [comment]
It is a large scale change. Please add some tests to ensure correctness.

**Comment by skiyer** [comment]
It seems that only the CIDR calculator function needs to be tested, since other functions were just copied from the original code.

**Comment by skiyer** [comment]
sorry for the delay BTW ;-)

**Pull request merged**
